import { FileCode, Copy, Check, RefreshCw, Download } from "lucide-react"
import { useEffect, useState } from "react"
import { exportMarkdown } from "../../utils/export"

// --- BUILD MARKDOWN FUNCTION ---
function buildMarkdown(inv) {
    const {
        title, type, severity, description, tags, id, createdAt,
        notes, sources, malware, actors, ttps, iocs, detections
    } = inv

    const lines = []
    const d  = v  => v || "N/A"
    const h  = (n, t) => lines.push(`${"#".repeat(n)} ${t}`)
    const br = () => lines.push("")

    h(1, title)
    br()
    lines.push(`**ID:** \`${id}\`  `)
    lines.push(`**Type:** ${d(type)}  `)
    lines.push(`**Severity:** ${d(severity)}  `)
    lines.push(`**Created:** ${new Date(createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}  `)
    if (tags?.length) lines.push(`**Tags:** ${tags.map(t => `\`${t}\``).join(", ")}  `)
    br()

    if (description) {
        h(2, "Overview")
        br()
        lines.push(description)
        br()
    }

    if (notes) {
        h(2, "Investigation Notes")
        br()
        lines.push(notes)
        br()
    }

    if (sources?.length) {
        h(2, "Source Material")
        br()
        sources.forEach(s => {
            lines.push(`### ${s.title}`)
            lines.push(`- **Type:** ${s.type}`)
            if (s.url)  lines.push(`- **URL:** ${s.url}`)
            if (s.date) lines.push(`- **Date:** ${s.date}`)
            lines.push(`- **TLP:** TLP:${s.tlp}`)
            lines.push(`- **Relevance:** ${s.relevance}`)
            if (s.notes) lines.push(`- **Notes:** ${s.notes}`)
            if (s.rawContent) {
                br()
                lines.push("```")
                lines.push(s.rawContent)
                lines.push("```")
            }
            br()
        })
    }

    if (actors?.length) {
        h(2, "Threat Actors")
        br()
        actors.forEach(a => {
        lines.push(`### ${a.name}`)
        if (a.aliases)    lines.push(`- **Aliases:** ${a.aliases}`)
        if (a.origin)     lines.push(`- **Origin:** ${a.origin}`)
        if (a.motivation) lines.push(`- **Motivation:** ${a.motivation}`)
        if (a.notes)      lines.push(`- **Notes:** ${a.notes}`)
        br()
        })
    }

    if (malware?.length) {
        h(2, "Malware Families")
        br()
        lines.push("| Name | Family | Type | Notes |")
        lines.push("|------|--------|------|-------|")
        malware.forEach(m => lines.push(`| ${d(m.name)} | ${d(m.family)} | ${d(m.type)} | ${d(m.notes)} |`))
        br()
    }

    if (ttps?.length) {
        h(2, "MITRE ATT&CK TTPs")
        br()
        lines.push("| Technique ID | Name | Tactic | Notes |")
        lines.push("|-------------|------|--------|-------|")
        ttps.forEach(t => lines.push(`| ${d(t.techniqueId)} | ${d(t.techniqueName)} | ${d(t.tactic)} | ${d(t.notes)} |`))
        br()
    }

    if (iocs?.length) {
        h(2, "Indicators of Compromise")
        br()
        lines.push("| Type | Value | TLP | Context |")
        lines.push("|------|-------|-----|---------|")
        iocs.forEach(i => lines.push(`| ${d(i.type)} | \`${d(i.value)}\` | TLP:${d(i.tlp)} | ${d(i.context)} |`))
        br()
    }

    if (detections?.length) {
        h(2, "Detections")
        br()
        detections.forEach(det => {
            lines.push(`### ${det.title}`)
            lines.push(`**Platform:** ${det.platform}  `)
            if (det.notes) lines.push(`**Notes:** ${det.notes}  `)
            if (det.rule) {
                br()
                lines.push("```")
                lines.push(det.rule)
                lines.push("```")
            }
            br()
        })
    }

    lines.push("---")
    lines.push(`*Generated by sdpcti — ${new Date().toISOString()}*`)

    return lines.join("\n")
}

export default function ReportSection({ inv }) {
    const [md,     setMd]     = useState("")
    const [copied, setCopied] = useState(false)

    function regenerate() { setMd(buildMarkdown(inv)) }

    useEffect(() => {regenerate() }, [])

    function copy() {
        navigator.clipboard.writeText(md);
        setCopied(true);
        setTimeout(() => setCopied(false), 1500);
    }

    function download() {
        exportMarkdown(inv.title, md);
    }

    return (
        <div className="section-panel">
            {/* Header */}
            <div className="section-header">
                <FileCode size={14} className="section-icon" />
                <h3 className="section-title">Report — Markdown</h3>
                <div style={{ display: "flex", gap: 6, marginLeft: "auto" }}>
                <button className="btn-section-add" onClick={regenerate}>
                    <RefreshCw size={12} /> Regenerate
                </button>
                <button className="btn-section-add" onClick={copy}>
                    {copied
                    ? <><Check size={12} style={{ color: "#34d399" }} /> Copied</>
                    : <><Copy size={12} /> Copy</>
                    }
                </button>
                <button className="btn-section-add btn-section-add--accent" onClick={download}>
                    <Download size={12} /> Download .md
                </button>
                </div>
            </div>
            <p className="section-sub">
                Auto-generated from all investigation sections. Edit directly or regenerate to sync.
            </p>
            <textarea
                className="notes-editor report-editor"
                value={md}
                onChange={e => setMd(e.target.value)}
                spellCheck={false}
            />
        </div>
    )
}